# Generated by Django 3.0.3 on 2020-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_studygroup_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='study_group',
        ),
        migrations.AddField(
            model_name='teacher',
            name='study_groups',
            field=models.ManyToManyField(to='users.StudyGroup'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='users.Subject'),
        ),
    ]
