# Generated by Django 3.0.3 on 2020-05-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200310_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervariant',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='name',
        ),
    ]
