# Generated by Django 3.0.3 on 2020-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200511_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervariant',
            name='next_question',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='multiple_apply',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SO', 'Select question'), ('ST', 'Text question')], max_length=2),
        ),
    ]
