# Generated by Django 3.0.3 on 2020-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200515_1612'),
        ('surveys', '0004_auto_20200515_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='audience',
            field=models.ManyToManyField(to='users.StudyGroup'),
        ),
    ]
