# Generated by Django 3.0.3 on 2020-06-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='audience',
        ),
    ]
