# Generated by Django 3.0.3 on 2020-06-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_answerselectalt_answertextalt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertext',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answertext',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answerselectalt',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='answertextalt',
            name='survey',
        ),
        migrations.DeleteModel(
            name='AnswerSelect',
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
    ]
