# Generated by Django 3.0.3 on 2020-06-08 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0009_auto_20200608_1309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerselect',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='answertext',
            unique_together={('user', 'question')},
        ),
    ]
